# 高维可视化数据
高维的数据可视化，添加更多的维度，在二维的屏幕上绘制高维图表。  
为散点图（Scatter Plot）添加⼀个维度  

【案例】为散点图增加新的维度  

如果我们要绘制一个散点图，并且希望根据另一个变量以某种方式区分这些点，那么您有几个选择。  

正如视频中所讨论的那样，在 2D 屏幕上使用 3D 图通常效果都很糟糕，很难选择好的视角。  

于是，我们讨论了其他选择，既可以保持使用 x-y 轴的平面坐标系，又可以可视化第三维的数据。  

我们可以更改点的颜色（Color），大小（Size），透明度（Transparency）或形状（Shape），或将图分成多个数据面板（Panel）。  

每行展示一位运动员在三个社交平台上的指标数据：Facebook，Instagram 和 Twitter 上的关注者数量。  

在这个案例中，我们会再次使用到在第 2 章中首次使用的北京二手房价数据集。    
探索不同的方法来区分四个城区的二手房交易数据，然后确定哪个表述是错误的。  

运行下面的脚本，在 “选择合适的方式区别不同的城区” 下拉菜单中选择区分方式，并找到区分度最好的方式。

In [1]:
import pandas as pd
import sys
sys.path.append('./data/course_data/visualization')
from dvfe_03_01 import interact_housing_price_app
interact_housing_price_app()

ModuleNotFoundError: No module named 'dvfe_03_01'

编写案例所使用的数据集，可以通过运行下面的脚本来查看。

In [3]:
import pandas as pd
df = pd.read_csv('./data/course_data/visualization/second_hand_housing_2016_after_2010_sample.csv', index_col=0)
df.info()
df.head(5)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2000 entries, 1938 to 39909
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   community_id                    2000 non-null   float64
 1   trade_time                      2000 non-null   object
 2   days_on_market                  2000 non-null   int64
 3   total_price                     2000 non-null   float64
 4   unit_price                      2000 non-null   int64
 5   area_sqm                        2000 non-null   float64
 6   n_bed_room                      2000 non-null   int64
 7   n_living_room                   2000 non-null   int64
 8   n_kitchen                       2000 non-null   int64
 9   n_bathroom                      2000 non-null   int64
 10  building                        2000 non-null   object
 11  building_type                   2000 non-null   object
 12  construction_time               2000 non-null   int64
 13  renovation_condition            2000 non-null   object
 14  building_structure              2000 non-null   object
 15  ladder_ratio                    2000 non-null   float64
 16  elevator                        2000 non-null   int64
 17  property_rights_for_five_years  2000 non-null   int64
 18  subway                          2000 non-null   int64
 19  district                        2000 non-null   object
 20  community_average               2000 non-null   int64
dtypes: float64(4), int64(11), object(6)
memory usage: 343.8+ KB

,community_id,trade_time,days_on_market,total_price,unit_price,area_sqm,n_bed_room,n_living_room,n_kitchen,n_bathroom,...,building_type,construction_time,renovation_condition,building_structure,ladder_ratio,elevator,property_rights_for_five_years,subway,district,community_average
1938,1.111030e+12,2016-08-15,158,9.75,42977,226.87,4,2,1,3,...,板塔结合,2009,精装,钢混,1.000,1,1,1,朝阳,51255
55757,1.111030e+12,2016-03-31,1,3.15,33904,92.91,2,2,1,1,...,板塔结合,2006,简装,钢混,0.500,1,1,0,朝阳,46072
19825,1.111030e+12,2016-07-29,14,6.15,73215,84.00,2,2,1,1,...,板塔结合,2007,其他,钢混,0.333,1,0,1,朝阳,82517
12642,1.111030e+12,2016-08-08,55,7.32,81569,89.74,2,1,1,1,...,板塔结合,2004,精装,钢混,0.250,1,1,1,西城,89350
18317,1.111030e+12,2016-08-11,34,2.80,46870,59.74,1,1,1,1,...,塔楼,2011,精装,钢混,0.300,1,0,1,朝阳,56336

选择题  
请大家阅读下面的选项，并找到描述 “错误” 的一项：  
A. 使用不同的大小或透明度很难区分重叠的点。  
B. 使用单独的面板提供了区分每个城区的最佳方法，但是使我们更难判断整个数据集中是否存在单一趋势。  
C. 使用不同的形状提供了区分每个城区的最佳方法，但是却很难查看整个数据集中是否存在单一趋势。  
D. 使用不同的颜色是区分每个城区的可行方法，但是在白色背景上很难看到较浅的颜色，而且无法避免点之间的重叠。  

恭喜您，答对了！应该选C，C项描述错误！
使用形状的方式并不能明确的区分点。

在这个案例中，由于数据集中的点并不能很好的聚集成多个区域，所以通过不同的 “数据面板” 绘制数据子集可能是最好的方法了。  

“颜色” 的区分方法有些差强人意，黑色和紫色区分度不高，白色背景黄色的点不明显等等。不过还是可以看到一些洞察，例如朝阳区的二手房交易最多，东城和西城的二手房交易价格更高等等。  

“大小” 和 “透明度” 显然不是合理的区分方式。  
为折线图（Line Plot）添加⼀个维度  

【案例】为折线图增加一个维度    

与散点图中的点一样，我们可能经常希望能够区分线图中的多条线。  

与散点图中的点一样的是，我们可以更改线的颜色（Color）、透明度（Transparency），或使用多个数据面板。  

与点的两个区别是，我们可以更改线宽（Width）而不是点大小（Size），还可以更改线型（Linetype，实线、虚线或点线等）而不是点形状（Shape）。  

接下来的线形图中显示了五个科技公司（统称为 “FAAMG”）的股价：Facebook（FB），Apple（AAPL），Amazon（AMZN），Microsoft（MSFT）和 Google（GOOG）。  

股票价格已针对股息和拆股进行了调整，然后相对于一段时间内的最高价格进行了缩放（缩放到相对于最高价格的 0～1 的数值），使得更容易进行比较。  

运行下面的脚本，探索不同的选项来区分五家公司，然后确定哪个描述是错误的。  

本案例数据来源：[雅虎财经](https://finance.yahoo.com/)  

运行下面的脚本，并在 “选择合适的方式区别不同的公司：” 下拉菜单中选择合适的区分方式...

In [ ]:
import pandas as pd
import sys
sys.path.append('/data/course_data/visualization')
from dvfe_03_02 import interact_stock_price_app
interact_stock_price_app()

数据集全部来自于雅虎财经，例如 Facebook, Inc.(FB) 的股票数据可以在 [这个连接](https://finance.yahoo.com/quote/FB/history?period1=1483228800&period2=1593993600&interval=1d&filter=history&frequency=1d) 中下载得到。  
选择题  
根据绘图中的数据，下面哪个说法是错误的？  
A. 所有五家公司在 2018 年初的价格都比 2017 年初的价格高。  
B. 在 2018 年，Facebook 的股价跌幅比其他任何公司都大。  
C. 从 2019 年初到 2020 年初，苹果的股价翻了一番还多。  
D. 到 2020 年，所有五家公司的价格都比他们在 2019 年上半年的价格更高。  

恭喜您，答对了！应该选D，D项描述错误！  
在这个案例中，尝试使用不同的选项来区分线，直到找到一个选项可以轻松识别每个公司，不难看出 “颜色” 和 “数据面板” 都可以清晰的区分。  

在 x 轴上找到选项中提到的日期，然后查找适当的行或是 y 轴的坐标，或查看在股票价格线的指定时间段内上升还是下降？  

恭喜，您又学完了一课，希望您在学习中心里留下您的思考和学习笔记